export const SET_BEST_EFFORT = 'SET_BEST_EFFORT';
export const SET_CHART_DATA_SET = 'SET_CHART_DATA_SET';
export const SET_CHART_DATA_SET_TIMES = 'SET_CHART_DATA_SET_TIMES';
export const SET_DATA_INITIALIZED = 'SET_DATA_INITIALIZED';